// Shared placeables registry used by both the world editor and the
// home page. The editor lets the user drop these assets into the
// world; the home page reads the persisted list from localStorage
// and spawns them during the intro wave so the world the player
// drives through reflects every edit they've made.

import * as THREE from 'three';
import { FBXLoader } from 'three/examples/jsm/loaders/FBXLoader.js';
import { OBJLoader } from 'three/examples/jsm/loaders/OBJLoader.js';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { isRoadSource, buildRoadFromSource, ROAD_TILE } from './roads';

export const EDITOR_KEY = 'editor-placements';
// Procedural foliage is generated by a deterministic per-tile RNG.
// When the user trashes one of those instances we don't actually
// remove anything from the scatter — we add a `${defId}:${tileIdx}`
// tombstone here so both the editor and the home page can skip
// rendering that specific instance.
export const TOMBSTONE_KEY = 'editor-tombstones';

export function loadTombstones(): Set<string> {
  try {
    const raw = localStorage.getItem(TOMBSTONE_KEY);
    if (!raw) return new Set();
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) return new Set();
    return new Set(parsed.filter((s) => typeof s === 'string'));
  } catch { return new Set(); }
}
export function saveTombstones(s: Set<string>) {
  try { localStorage.setItem(TOMBSTONE_KEY, JSON.stringify([...s])); } catch { /* private mode */ }
}
export function tombstoneKey(defId: string, tileIdx: number): string {
  return `${defId}:${tileIdx}`;
}

export interface Placement {
  /** Stable id for the asset definition. */
  assetId: string;
  /** World position (Y derived per-load from the asset's bbox.min). */
  x: number;
  z: number;
  /** Multiplier on the asset's natural target size. */
  scale: number;
  /** Rotation around world Y. */
  rotY: number;
}

export type PlaceableCategory =
  | 'road'
  | 'tree' | 'foliage' | 'flower' | 'mushroom' | 'rock' | 'prop'
  | 'electronics' | 'aircraft';

export interface PlaceableDef {
  id: string;
  category: PlaceableCategory;
  label: string;
  dot: string;
  /** Natural max-dimension in world units when placed at scale = 1. */
  targetSize: number;
  /** Asset URL ("/models/foo.obj") OR a procedural prefix
   *  ("procedural:road-straight"). Loader chosen by the prefix. */
  source: string;
  /** Roads + grid-aligned props snap to the floor tile center on
   *  placement and rotate in 90° increments. Bypasses the per-frame
   *  free-cursor follow + the scale modifier (size = ROAD_TILE
   *  exactly so adjacent chunks meet flush). */
  snapToGrid?: boolean;
  /** When set on a GLB/GLTF asset, prune every mesh whose material
   *  name doesn't match. Pass a single name or a list (any-of) — lets
   *  us expose a sub-part of a multi-material model (e.g. the IBM
   *  terminal monitor: chassis + display, no keyboard) as its own
   *  placeable without splitting the asset file. */
  materialFilter?: string | string[];
  /** Drop every triangle whose world-Y centroid sits below
   *  `bbox.min.y + fraction * height`. Used to slice off the lower
   *  half of a model when the part we want shares a single mesh /
   *  material with the part we don't (e.g. removing the IBM 3178
   *  base from the monitor case — both are the same chassis mesh). */
  clipBelowYFraction?: number;
}

export const PLACEABLES: PlaceableDef[] = [
  // Roads — chunk-locked, snapped to the tile grid. ROAD_TILE matches
  // FLOOR_TILE_SIZE so each piece occupies exactly one tile.
  { id: 'RoadStraight', category: 'road', label: 'Road, Straight',  dot: '#9ca3af', targetSize: ROAD_TILE, source: 'procedural:road-straight', snapToGrid: true },
  { id: 'RoadCurve',    category: 'road', label: 'Road, Curve',     dot: '#9ca3af', targetSize: ROAD_TILE, source: 'procedural:road-curve',    snapToGrid: true },
  { id: 'RoadTee',      category: 'road', label: 'Road, T-junction', dot: '#9ca3af', targetSize: ROAD_TILE, source: 'procedural:road-tee',      snapToGrid: true },
  { id: 'RoadCross',    category: 'road', label: 'Road, 4-way',     dot: '#9ca3af', targetSize: ROAD_TILE, source: 'procedural:road-cross',    snapToGrid: true },
  // Trees
  { id: 'Tree1_Green', category: 'tree', label: 'Tree, Spruce A', dot: '#86efac', targetSize: 11, source: '/models/nature/Tree1_Green.obj' },
  { id: 'Tree2_Green', category: 'tree', label: 'Tree, Spruce B', dot: '#86efac', targetSize: 12, source: '/models/nature/Tree2_Green.obj' },
  { id: 'Tree3',       category: 'tree', label: 'Tree, Round',    dot: '#86efac', targetSize: 9,  source: '/models/nature/Tree3.obj' },
  { id: 'Tree4_Green', category: 'tree', label: 'Tree, Bushy A',  dot: '#86efac', targetSize: 8,  source: '/models/nature/Tree4_Green.obj' },
  { id: 'Tree5_Green', category: 'tree', label: 'Tree, Bushy B',  dot: '#86efac', targetSize: 8,  source: '/models/nature/Tree5_Green.obj' },
  { id: 'Tree6_Green', category: 'tree', label: 'Tree, Bushy C',  dot: '#86efac', targetSize: 10, source: '/models/nature/Tree6_Green.obj' },
  // Foliage
  { id: 'CircularBush_Green', category: 'foliage', label: 'Bush, Round',  dot: '#a3e635', targetSize: 2.4, source: '/models/nature/CircularBush_Green.obj' },
  { id: 'CubyBush_Green',     category: 'foliage', label: 'Bush, Cuboid', dot: '#a3e635', targetSize: 2.2, source: '/models/nature/CubyBush_Green.obj' },
  { id: 'Reed',               category: 'foliage', label: 'Reeds',        dot: '#84cc16', targetSize: 2.0, source: '/models/nature/Reed.obj' },
  // Flowers
  { id: 'Flower1', category: 'flower', label: 'Flower 1', dot: '#fb7185', targetSize: 0.8, source: '/models/nature/Flower1.obj' },
  { id: 'Flower2', category: 'flower', label: 'Flower 2', dot: '#fbbf24', targetSize: 0.8, source: '/models/nature/Flower2.obj' },
  { id: 'Flower3', category: 'flower', label: 'Flower 3', dot: '#a78bfa', targetSize: 0.7, source: '/models/nature/Flower3.obj' },
  { id: 'Flower4', category: 'flower', label: 'Flower 4', dot: '#22d3ee', targetSize: 0.7, source: '/models/nature/Flower4.obj' },
  { id: 'Flower5', category: 'flower', label: 'Flower 5', dot: '#f472b6', targetSize: 0.8, source: '/models/nature/Flower5.obj' },
  // Mushrooms
  { id: 'Mushroom1', category: 'mushroom', label: 'Mushroom A', dot: '#f87171', targetSize: 1.3, source: '/models/nature/Mushroom1.obj' },
  { id: 'Mushroom2', category: 'mushroom', label: 'Mushroom B', dot: '#f87171', targetSize: 1.0, source: '/models/nature/Mushroom2.obj' },
  // Rocks
  { id: 'Rock1', category: 'rock', label: 'Rock A', dot: '#9ca3af', targetSize: 2.5, source: '/models/nature/Rock1.obj' },
  { id: 'Rock2', category: 'rock', label: 'Rock B', dot: '#9ca3af', targetSize: 2.0, source: '/models/nature/Rock2.obj' },
  { id: 'Rock3', category: 'rock', label: 'Rock C', dot: '#9ca3af', targetSize: 1.8, source: '/models/nature/Rock3.obj' },
  { id: 'Rock4', category: 'rock', label: 'Rock D', dot: '#9ca3af', targetSize: 1.5, source: '/models/nature/Rock4.obj' },
  // Misc props
  { id: 'Worm',    category: 'prop', label: 'Worm',    dot: '#fb923c', targetSize: 1.0, source: '/models/nature/Worm.obj' },
  { id: 'Lilypad', category: 'prop', label: 'Lilypad', dot: '#34d399', targetSize: 1.2, source: '/models/nature/Lilypad.obj' },
  { id: 'Log1',    category: 'prop', label: 'Log A',   dot: '#a16207', targetSize: 2.0, source: '/models/nature/Log1.obj' },
  { id: 'Log2',    category: 'prop', label: 'Log B',   dot: '#a16207', targetSize: 2.5, source: '/models/nature/Log2.obj' },
  // Electronics
  { id: 'IBM_3178', category: 'electronics', label: 'IBM 3178', dot: '#a3a3a3', targetSize: 4, source: '/models/electronics/ibm_3178.glb' },
  // Monitor unit only — chassis (`ibm_3178`) + CRT panel (`display`),
  // keyboard mesh stripped. Same source GLB as the full terminal.
  // Chassis mesh contains BOTH the monitor case and the bottom base
  // box (single material), so we additionally clip the lower 28% of
  // the geometry — that's just below the case's rounded underside,
  // above the swivel/base. Higher fractions cut into the case and
  // expose the interior backfaces (case is a hollow shell).
  { id: 'IBM_3178_Monitor', category: 'electronics', label: 'IBM 3178 Monitor', dot: '#22d3ee', targetSize: 3, source: '/models/electronics/ibm_3178.glb', materialFilter: ['ibm_3178', 'display'], clipBelowYFraction: 0.28 },
  // Aircraft
  { id: 'Plane', category: 'aircraft', label: 'Plane', dot: '#a78bfa', targetSize: 4, source: '/models/aircraft/plane.glb' },
];

export function findPlaceable(id: string): PlaceableDef | undefined {
  return PLACEABLES.find((p) => p.id === id);
}

const fbxLoader = new FBXLoader();
const objLoader = new OBJLoader();
const glbLoader = new GLTFLoader();

/** Drop every triangle whose world-Y centroid sits below
 *  `bbox.min.y + fraction * height`. Compacts each mesh's attribute
 *  arrays to only the surviving vertices so the bbox afterwards is
 *  honest (computeBoundingBox reads the position attribute, not the
 *  index — leaving stale vertices in place would inflate it). */
export function clipBelowWorldYFraction(root: THREE.Object3D, fraction: number): void {
  root.updateMatrixWorld(true);
  const bbox = new THREE.Box3().setFromObject(root);
  if (!isFinite(bbox.min.y) || !isFinite(bbox.max.y)) return;
  const cutY = bbox.min.y + (bbox.max.y - bbox.min.y) * fraction;
  const v = new THREE.Vector3();
  const orphans: THREE.Mesh[] = [];
  root.traverse((node) => {
    const mesh = node as THREE.Mesh;
    if (!(mesh as any).isMesh) return;
    const src = mesh.geometry as THREE.BufferGeometry;
    const pos = src.attributes.position as THREE.BufferAttribute | undefined;
    if (!pos) return;
    const idx = src.index;
    const triCount = idx ? idx.count / 3 : pos.count / 3;
    const keepTris: number[] = [];
    for (let t = 0; t < triCount; t++) {
      const ia = idx ? idx.getX(t * 3)     : t * 3;
      const ib = idx ? idx.getX(t * 3 + 1) : t * 3 + 1;
      const ic = idx ? idx.getX(t * 3 + 2) : t * 3 + 2;
      // Require ALL three vertices above the cut. Centroid-only let
      // large triangles that span the cut survive, leaving "skirts"
      // hanging into the removed region.
      let allAbove = true;
      for (const i of [ia, ib, ic]) {
        v.set(pos.getX(i), pos.getY(i), pos.getZ(i)).applyMatrix4(mesh.matrixWorld);
        if (v.y <= cutY) { allAbove = false; break; }
      }
      if (allAbove) keepTris.push(ia, ib, ic);
    }
    if (keepTris.length === 0) {
      orphans.push(mesh);
      return;
    }
    if (keepTris.length === triCount * 3) return; // nothing dropped
    // Compact: build a remap so the new attribute arrays only carry
    // referenced vertices. Otherwise computeBoundingBox would still
    // include the dropped vertices.
    const remap = new Map<number, number>();
    const newIdx: number[] = [];
    for (const i of keepTris) {
      let n = remap.get(i);
      if (n === undefined) {
        n = remap.size;
        remap.set(i, n);
      }
      newIdx.push(n);
    }
    const newGeom = new THREE.BufferGeometry();
    for (const name of Object.keys(src.attributes)) {
      const srcAttr = src.attributes[name] as THREE.BufferAttribute;
      const itemSize = srcAttr.itemSize;
      const ArrCtor = (srcAttr.array as any).constructor;
      const newArr = new ArrCtor(remap.size * itemSize);
      for (const [origI, newI] of remap) {
        for (let c = 0; c < itemSize; c++) {
          newArr[newI * itemSize + c] = (srcAttr.array as any)[origI * itemSize + c];
        }
      }
      newGeom.setAttribute(name, new THREE.BufferAttribute(newArr, itemSize));
    }
    newGeom.setIndex(newIdx);
    newGeom.computeBoundingBox();
    newGeom.computeBoundingSphere();
    mesh.geometry = newGeom;
  });
  for (const m of orphans) m.removeFromParent();
}

let _naturePalette: THREE.Texture | null = null;
function getNaturePalette(): THREE.Texture {
  if (_naturePalette) return _naturePalette;
  const t = new THREE.TextureLoader().load('/models/nature/TexturePalette.png');
  t.colorSpace = THREE.SRGBColorSpace;
  t.magFilter = THREE.NearestFilter;
  t.minFilter = THREE.NearestFilter;
  t.generateMipmaps = false;
  _naturePalette = t;
  return t;
}

/** Load an asset by definition. Returns an Object3D with scale set so
 *  its largest natural dimension equals def.targetSize. The caller can
 *  then multiply by a per-instance scale factor and set position/rotation. */
export async function loadPlaceable(def: PlaceableDef): Promise<THREE.Object3D> {
  // Procedural assets (roads, etc.) skip the loader entirely: they
  // build their geometry on the fly at the exact target size, so we
  // also skip the bbox-fit normalization below.
  if (isRoadSource(def.source)) {
    return buildRoadFromSource(def.source);
  }
  const ext = def.source.split('.').pop()!.toLowerCase();
  let raw: THREE.Object3D;
  if (ext === 'obj') {
    raw = await objLoader.loadAsync(def.source);
  } else if (ext === 'glb' || ext === 'gltf') {
    const gltf = await glbLoader.loadAsync(def.source);
    raw = gltf.scene;
  } else if (ext === 'fbx') {
    raw = await fbxLoader.loadAsync(def.source);
  } else {
    throw new Error(`unknown extension for ${def.source}`);
  }
  // OBJ-loaded nature props ship with a generic gray .mtl; the
  // painted color lives in the shared TexturePalette UV sheet.
  if (ext === 'obj') {
    const palette = getNaturePalette();
    raw.traverse((node) => {
      const mesh = node as THREE.Mesh;
      if (!(mesh as any).isMesh) return;
      mesh.material = new THREE.MeshStandardMaterial({
        map: palette, roughness: 0.85, metalness: 0.05,
      });
    });
  }
  // Material filter: prune meshes whose material doesn't match. Done
  // *before* the bbox normalize below so the surviving sub-part fills
  // its targetSize on its own (e.g. the display panel scales to 2.5
  // units, ignoring the chassis it was packaged with).
  if (def.materialFilter) {
    const allow = new Set(Array.isArray(def.materialFilter) ? def.materialFilter : [def.materialFilter]);
    const keep: THREE.Mesh[] = [];
    raw.traverse((node) => {
      const mesh = node as THREE.Mesh;
      if (!(mesh as any).isMesh) return;
      const mat = mesh.material as THREE.Material | THREE.Material[];
      const name = Array.isArray(mat) ? mat[0]?.name : mat?.name;
      if (name && allow.has(name)) keep.push(mesh);
    });
    const filtered = new THREE.Group();
    filtered.name = `${raw.name || 'asset'}-filtered`;
    for (const src of keep) {
      // Clone (geometry/material refs reused — cheap) so we don't
      // detach nodes from a tree the GLTFLoader may hand to another
      // caller. Bake world transform onto the clone so the new parent
      // group doesn't have to inherit the GLB's rotation/scale chain.
      src.updateWorldMatrix(true, false);
      const m = src.clone(false);
      m.matrix.copy(src.matrixWorld);
      m.matrix.decompose(m.position, m.quaternion, m.scale);
      filtered.add(m);
    }
    raw = filtered;
  }
  if (def.clipBelowYFraction !== undefined) {
    clipBelowWorldYFraction(raw, def.clipBelowYFraction);
  }
  const box = new THREE.Box3().setFromObject(raw);
  const size = new THREE.Vector3();
  box.getSize(size);
  const maxDim = Math.max(size.x, size.y, size.z);
  if (maxDim > 0) raw.scale.multiplyScalar(def.targetSize / maxDim);
  return raw;
}

export function loadStoredPlacements(): Placement[] {
  try {
    const raw = localStorage.getItem(EDITOR_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    return parsed.filter((p) => p && typeof p.assetId === 'string');
  } catch { return []; }
}
export function saveStoredPlacements(items: Placement[]) {
  try { localStorage.setItem(EDITOR_KEY, JSON.stringify(items)); } catch { /* private mode */ }
}
